apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-volume
              mountPath: "/tmp/here"
              readOnly: true
        - name: proxy
          image: some-proxy
          volumeMounts:
            - name: my-volume
              mountPath: "/tmp/here"
              readOnly: true
        - name: another
          image: another-proxy
          volumeMounts:
            - name: my-volume
              mountPath: "/tmp/here"
              readOnly: true
      volumes:
        - name: my-volume
          configMap:
            name: my-volume
